# Copyright (c) 2025 Fabstir
# SPDX-License-Identifier: BUSL-1.1

apiVersion: v1
kind: Service
metadata:
  name: fabstir-host-service
  namespace: fabstir-host
  labels:
    app: fabstir-host
spec:
  type: NodePort
  selector:
    app: fabstir-host
  ports:
  # API/Health/WebSocket port
  - name: api
    protocol: TCP
    port: 8083
    targetPort: 8083
    # NodePort will be auto-assigned in range 30000-32767
    # Access via: http://209.250.225.219:<nodePort>

  # P2P communication port
  - name: p2p
    protocol: TCP
    port: 9000
    targetPort: 9000

  # Management API port
  - name: management
    protocol: TCP
    port: 3001
    targetPort: 3001

  # Ensure service routes to GPU node where pod is running
  externalTrafficPolicy: Local
